spring.application.name=brewledger-backend

server.port=8081

spring.datasource.url=YOUR_SUPABASE_URL
spring.datasource.username=YOUR_SUPABASE_USERNAME
spring.datasource.password=YOUR_SUPABASE_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

brewledger.admin.full-name=Administrator
brewledger.admin.username=admin
brewledger.admin.password=change-me

jwt.secret=CHANGE_ME_TO_LONG_SECRET_KEY
jwt.expiration=86400000