spring.application.name=brewledger-backend

spring.profiles.default=dev

server.port=${SERVER_PORT:8081}

jwt.expiration=${JWT_EXPIRATION:86400000}

# Telegram Notifications
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.chat.id=${TELEGRAM_CHAT_ID:}
